### ISSUE TITLE
rpmbuild报错

### ISSUE THREAD

**Issue by xmjlong** [xiaomatech/toa#1]
环境为vmware 虚拟化   CentOS6.8x64

rpmbuild报错如下 

+ for cfg in 'kernel-2.6.32-*.config'
++ echo kernel-2.6.32-x86_64-debug.config kernel-2.6.32-x86_64.config
++ grep -c kernel-2.6.32-x86_64.config
+ '[' 1 -eq 0 ']'
+ for i in '*.config'
+ mv kernel-2.6.32-x86_64-debug.config .config
++ head -1 .config
++ cut -b 3-
+ Arch=x86_64
+ make ARCH=x86_64 nonint_oldconfig
CONFIG_HOOKERS
CONFIG_TOA
CONFIG_DM_FLASHCACHE
make[1]: *** [nonint_oldconfig] Error 3
make: *** [nonint_oldconfig] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.ZTIIlV (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.ZTIIlV (%prep)

另外，在ReadMe里

toa.patch
    source https://github.com/alibaba/ali_kernel_rpm/blob/6u/patches.taobao/toa.patch

    alibaba toa patch in centos 6.8/7.2

这一步，是说要先打这个patch吗

**Comment by xianhuawei** [comment]
阿里的这个patch只支持2.6系列的, 不支持6.8/7.2

**Comment by xmjlong** [comment]
这篇文章里提供的不就是 6.8和7.2版本的patch吗

**Comment by xianhuawei** [comment]
是的  要先patch

**Comment by xmjlong** [comment]
那步骤上是否应该是先安然内核源码，然后两个patch一起打，然后在build?

rpm -ivh http://vault.centos.org/centos/6//updates/Source/SPackages/kernel-2.6.32-642.11.1.el6.src.rpm
cd ~/rpmbuild/SOURCES
tar -jxvf linux-2.6.32-642.11.1.el6.tar.bz2

wget https://raw.githubusercontent.com/xiaomatech/toa/master/centos6.8-toa.patch
wget https://github.com/alibaba/ali_kernel_rpm/blob/6u/patches.taobao/toa.patch
cd linux-2.6.32-642.11.1.el6
patch -p1 < ~/rpmbuild/SOURCES/centos6.8-toa.patch
patch -p1 < ~/rpmbuild/SOURCES/toa.patch
.....

像这样？

**Comment by dhh123** [comment]
hello ，有打好的rpm包吗？我也遇到了类似错误
